"""initial_core_tables

Revision ID: eb85a8f3b3bb
Revises: 
Create Date: 2026-03-09 04:59:53.250619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb85a8f3b3bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('language_pref', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('case_study_id', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'live', 'uploaded', 'processing', 'completed', 'failed', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('artifact_manifest_path', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=20), nullable=True),
    sa.Column('processing_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('audio_raw', 'video_raw', 'transcript_raw', 'transcript_canonical', 'frame_bundle', 'audio_features', 'video_features', 'content_features', 'evidence_graph', 'profile', name='artifact_type'), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('construct_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('supported', 'mixed', 'weak', name='hypothesis_status'), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('evidence_refs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('profile_version', sa.String(length=20), nullable=False),
    sa.Column('student_view_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('counsellor_view_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('school_view_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('red_flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_windows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('topic_key', sa.String(length=100), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source_turn_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('student', 'counsellor', 'system', name='speaker_type'), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('live_transcript', 'fallback_transcript', 'manual', name='transcript_source'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('window_id', sa.UUID(), nullable=True),
    sa.Column('modality', sa.Enum('content', 'audio', 'video', 'cross_modal', name='modality_type'), nullable=False),
    sa.Column('signal_key', sa.String(length=100), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ref_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['signal_windows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_observations')
    op.drop_table('turns')
    op.drop_table('signal_windows')
    op.drop_table('profiles')
    op.drop_table('hypotheses')
    op.drop_table('artifacts')
    op.drop_table('sessions')
    op.drop_table('students')
    op.drop_table('schools')
    # ### end Alembic commands ###
