"""Session retrieval and profile API routes."""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from counselai.api.deps import get_db
from counselai.api.schemas import (
    ProfileResponse,
    SessionDetailResponse,
    SessionStatus,
)
from counselai.storage.repositories.sessions import SessionRepository

router = APIRouter()


@router.get("/{session_id}", response_model=SessionDetailResponse)
def get_session(session_id: str, db: Session = Depends(get_db)):
    """Return session summary and processing status."""
    try:
        sid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session_id format")

    repo = SessionRepository(db)
    session = repo.get(sid)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found")

    return SessionDetailResponse(
        session_id=session.id,
        student_id=session.student_id,
        case_study_id=session.case_study_id,
        provider=session.provider,
        status=SessionStatus(session.status.value),
        started_at=session.started_at,
        ended_at=session.ended_at,
        duration_seconds=session.duration_seconds,
        primary_language=session.primary_language,
        processing_version=session.processing_version or "v1",
    )


@router.get("/{session_id}/profile", response_model=ProfileResponse)
def get_session_profile(session_id: str, db: Session = Depends(get_db)):
    """Return bounded profile output.

    The profile is generated by the synthesis engine (Task 11).
    This route returns the counsellor-facing view shaped for the API contract.
    """
    # TODO: wire to profile repository — Task 11+
    raise HTTPException(status_code=501, detail="Profile synthesis not yet implemented")
