"""Session retrieval and profile API routes."""

from __future__ import annotations

import uuid

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from counselai.api.deps import get_db
from counselai.api.schemas import (
    CognitiveProfileSnapshot,
    CounsellorEffectiveness,
    EmotionalIndicators,
    ProfileResponse,
    RecommendedFollowups,
    RiskFlags,
    SessionDetailResponse,
    SessionReportResponse,
    SessionStatus,
    ThemeItem,
)
from counselai.storage.repositories.sessions import SessionRepository

router = APIRouter()


@router.get("/{session_id}", response_model=SessionDetailResponse)
async def get_session(session_id: str, db: AsyncSession = Depends(get_db)):
    """Return session summary and processing status."""
    try:
        sid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session_id format")

    repo = SessionRepository(db)
    session = await repo.get(sid)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found")

    return SessionDetailResponse(
        session_id=session.id,
        student_id=session.student_id,
        case_study_id=session.case_study_id,
        provider=session.provider,
        status=SessionStatus(session.status.value),
        started_at=session.started_at,
        ended_at=session.ended_at,
        duration_seconds=session.duration_seconds,
        primary_language=session.primary_language,
        processing_version=session.processing_version or "v1",
    )


@router.get("/{session_id}/report", response_model=SessionReportResponse)
async def get_session_report(
    session_id: str,
    force: bool = False,
    db: AsyncSession = Depends(get_db),
):
    """Generate or retrieve a post-session report.

    Pass ?force=true to regenerate even if a cached report exists.
    """
    try:
        sid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session_id format")

    repo = SessionRepository(db)
    session = await repo.get(sid)
    if session is None:
        raise HTTPException(status_code=404, detail="Session not found")

    from counselai.analysis.report_generator import generate_report

    try:
        report = await generate_report(db, sid, force=force)
    except RuntimeError as exc:
        raise HTTPException(status_code=500, detail=str(exc))

    await db.commit()

    return SessionReportResponse(
        session_id=sid,
        session_summary=report.session_summary,
        student_engagement_score=report.student_engagement_score,
        student_engagement_rationale=report.student_engagement_rationale,
        key_themes=[
            ThemeItem(theme=t.get("theme", ""), evidence=t.get("evidence", ""))
            for t in report.key_themes
        ],
        emotional_indicators=EmotionalIndicators(**report.emotional_indicators)
        if report.emotional_indicators
        else EmotionalIndicators(),
        risk_flags=RiskFlags(**report.risk_flags)
        if report.risk_flags
        else RiskFlags(),
        counsellor_effectiveness=CounsellorEffectiveness(**report.counsellor_effectiveness)
        if report.counsellor_effectiveness
        else CounsellorEffectiveness(),
        recommended_followups=RecommendedFollowups(**report.recommended_followups)
        if report.recommended_followups
        else RecommendedFollowups(),
        cognitive_profile_snapshot=CognitiveProfileSnapshot(**report.cognitive_profile_snapshot)
        if report.cognitive_profile_snapshot
        else CognitiveProfileSnapshot(),
    )


@router.get("/{session_id}/profile", response_model=ProfileResponse)
async def get_session_profile(session_id: str, db: AsyncSession = Depends(get_db)):
    """Return bounded profile output.

    The profile is generated by the synthesis engine (Task 11).
    This route returns the counsellor-facing view shaped for the API contract.
    """
    # TODO: wire to profile repository — Task 11+
    raise HTTPException(status_code=501, detail="Profile synthesis not yet implemented")
